application:
  port: 8000
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "localhost"
  sender_email: "test@tgmail.com"
  authorization_token: "a8a13fc7-b4ce-4623-abc2-f648db44fde6"
  timeout_milliseconds: 10000